### ISSUE TITLE
Buttons Bouncing back

### ISSUE THREAD

**Issue by dbgnu76** [TheMrBooyah/hassio-dirigera-client#7]
Hi,

i have some trouble that light buttons works for a while, then suddenly they will be bouncing back in Home Assistant and
sometime few works and some bounce back.
and when this is happening status will not be updated.

Then i have to restart addon and sometimes HA, it is very annoying.

any idea what is going on ?

**Comment by TheMrBooyah** [comment]
Could you share the log for it when this happens?

**Comment by dvdgeisler** [comment]
Most likely, the connection between the Dirigera service and MQTT was broken and not successfully restored. I have already implemented a workaround to fix this problem, however, its not yet available in the current release (0.1.0). The workaround attempts to restart the service when the connection to MQTT is broken.

Hence, releasing the current state might already solve the problem.
Nevertheless, a sharing the logs (also from the MQTT) could provide us with further certainty.

**Comment by dbgnu76** [comment]
I will try to retreive some log, i was trying this morning, but there was no log infact program was not running, but still it stated it was. The green dot was there but the cpu and memory was zero. And the switches was bouncing.![Screenshot_20230106_064237_Home Assistant.jpg](https://user-images.githubusercontent.com/43219792/210947486-fb76dc48-3ef8-474a-9b64-4750a3071077.jpg)

**Comment by TheMrBooyah** [comment]
This does sound like the issue @dvdgeisler mentioned. Could be a good idea to release a patch for it to incorporate in the addon

**Comment by dvdgeisler** [comment]
I just created the release v0.1.1
It provides some mechanics to make the connection more resilient.

**Comment by TheMrBooyah** [comment]
~Builds are running for an image with v0.1.1.~
New images with v0.1.1 are available! Update to version 2023.1.12 of the addon.
@dbgnu76 Let us know if this fixes your issue

**Comment by sidneycmd** [comment]
Was having the same issue as @dbgnu76 and the 2023.1.12 update fixed it for me. Thank you!
